# Generated by Django 2.1.7 on 2019-03-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Website', 'Website'), ('Logo', 'Logo'), ('App', 'App'), ('Flyer', 'Flyer'), ('Business Card', 'Business Card')], default=None, max_length=13, verbose_name='Project Type')),
                ('date', models.CharField(blank=True, max_length=255, verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/work/projects')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Client', verbose_name='Client Name')),
                ('skills', models.ManyToManyField(blank=True, to='skillset.Skill', verbose_name='Technologies Used')),
                ('software', models.ManyToManyField(blank=True, to='skillset.Software', verbose_name='Software Used')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
