# Generated by Django 2.1.7 on 2019-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
